config/routes.rb
Bajiao::Application.routes.draw do
  root :to => "home#show"
  
  resources :users
  resources :user_photos

end

app/models/tmp_user.rb
#encoding:utf-8
class TmpUser < ActiveRecord::Base
  #批量创建tmp_user
  def self.batch_create(staffs)
    self.transaction do
      TmpUser.delete_all
      TmpUser.connection.execute("ALTER TABLE tmp_users AUTO_INCREMENT=1")
      #为了效率，组装一个大SQL一次执行
      #time = Time.now.strftime("%Y-%m-%d %H:%M:%S")
      sql_arr = []
      staffs.each do |s|
        sql = []
        %w(cnname workno email phone dept py duty).each do |k|
          sql << s[k]
        end
        #sql << time
        #sql << time
        sql_str = sql.map { |i| i.is_a?(Fixnum) ? i : '"' + i + '"' }.join(",")
        sql_arr << "(" + sql_str + ")"
      end
      TmpUser.connection.execute "INSERT INTO tmp_users(cnname,workno,email,phone,dept,py,duty) values #{sql_arr.join(", ")}"
    end
  end
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base
  scope :quit, where(:quit=>true)
  scope :onjob, where(:quit=>false)

  #根据tmp_users表更新自己
  def self.update_data
    #处理在职员工的离职或变动情况
    User.onjob.each do |user|
      tmp_user = TmpUser.where(:workno=>user.workno).first
      if tmp_user
        if user.update_by_tmpuser(tmp_user)
          puts  "update user #{user.cnname}"
        end
        tmp_user.delete
      else
        #处理离职
        user.update_attributes(:quit=>true)
        puts "quit user #{user.cnname}"
      end
    end

    #处理离职员工的重修情况
    User.quit.each do |user|
      tmp_user = TmpUser.where(:workno=>user.workno).first
      if tmp_user
        user.update_by_tmpuser(tmp_user)
        user.quit = false
        user.re_created_at = Time.now
        user.save
        tmp_user.delete
        puts "reonjob user #{user.cnname}"
      end
    end

    #处理入职新员工的情况
    TmpUser.all.each do |tmp_user|
      User.create(tmp_user.attributes.except("updated_at", "created_at"))
      tmp_user.delete
      puts "new user #{tmp_user.cnname}"
    end

    return true
  end

  #更新图片的id
  def self.update_photo_id
    User.all.each do |user|
      photo = UserPhoto.where(:workno=>user.workno).first
      if photo
        user.update_attributes(:user_photo_id=>photo.id)
      else
        user.update_attributes(:user_photo_id=>nil)
      end
    end
    return true
  end

  #根据tmp_users的数据更新自己
  def update_by_tmpuser(tmp_user)
    is_same = true
    [:cnname, :workno, :email, :phone, :dept, :py, :duty].each do |f|
      if tmp_user.send(f) != self.send(f)
        is_same = false
        break
      end
    end
    unless is_same
      self.update_attributes(tmp_user.attributes.except("updated_at", "created_at"))
    end
    return !is_same
  end

end

app/models/user_photo.rb
require "digest/sha2"
class UserPhoto < ActiveRecord::Base
  before_save :make_digest

  def make_digest
    self.digest = Digest::SHA2.hexdigest(self.data)
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def show
    
  end
  
end

app/controllers/user_photos_controller.rb
#encoding:utf-8
class UserPhotosController < ApplicationController
  def index
    @photos = UserPhoto.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photos.to_json(:only=>[:digest,:workno]) }
    end
  end

  def show
    @photo = UserPhoto.find(params[:id])
    send_data @photo.data, :type => 'image/jpeg'
  end

  def create
    data =  params[:file]
    workno = params[:workno]
    @photo = UserPhoto.where(:workno=>workno).first
    if @photo
      @photo.update_attributes(:data=>data.read)
    else
      UserPhoto.create(:workno=>workno, :data=>data.read)
    end
    render :text=>"ok"
  end

end

app/controllers/users_controller.rb
#encoding:utf-8
class UsersController < ApplicationController
  def index
    if %w[onjob quit newbie].include?(params[:type])
      @users = User.send(params[:type])
    else
      @users = User.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json do
        render :json=> @users.to_json
      end
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json do
        render :json => @user.to_json(:only=>[:cnname, :workno, :email, :phone, :dept, :py, :duty, :user_photo_id])
      end
    end
  end

  # 接受脚本上传的JSON数据
  def create
    if params[:secret] == "wocaonima"
      staffs = ActiveSupport::JSON.decode(params[:staffs])
      TmpUser.batch_create(staffs)
      Thread.new do
        User.update_data
        User.update_photo_id
        Version.create(:time=>Time.now)
      end
    end
    render :text=>"update ok!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ball_helper.rb
module BallHelper
end

app/views/home/_about.html.erb
<div class="popMask" style="display:none">
  <div id="aboutPop" class="layer">
    <header>关于</header>
    <article>
      <div>作者：葛亮</div>
      <div>版本：xxxxxxx</div>
    </article>
  </div>
</div>

app/views/home/_detail.html.erb
<section class="card" id="detail">
  <header>
    <div class="button back">
      <p>返回</p>
      <div><span></span></div>
    </div>
    <h2>员工详情</h2>
    <div style="width:70px;"></div>
  </header>
  <article id="detailPanel">
    <div>
    <img id="staffPhoto" />
    <ul id="staffDetail">
        <li>
          <label>姓名</label>
          <span></span>
        </li>
        <li>
          <label>分机号</label>
          <span></span>
        </li>
        <li>
          <label>Email</label>
          <span></span>
        </li>
        <li>
          <label>部门</label>
          <span></span>
        </li>
        <li>
          <label>职位</label>
          <span></span>
        </li>
        <li>
          <label>工号</label>
          <span></span>
        </li>
    </ul>
    </div>
  </article>
</section>

app/views/home/_letter_ime.html.erb
<div id="ime">
  <table cellpadding="0" cellspacing="0" style="display:none">
    <col width="25%"/>
    <col width="25%"/>
    <col width="25%"/>
    <col width="25%"/>
    <tr>
      <td style="font-size:10px">英/数/中</td>
      <td colspan="3" id="imeText"></td>
    </tr>
    <tr>
      <td>A</td>
      <td>B</td>
      <td>C</td>
      <td>D</td>
    </tr>
    <tr>
      <td>E</td>
      <td>F</td>
      <td>G</td>
      <td>H</td>
    </tr>
    <tr>
      <td>I</td>
      <td>J</td>
      <td>K</td>
      <td>L</td>
    </tr>
    <tr>
      <td>M</td>
      <td>N</td>
      <td>O</td>
      <td>P</td>
    </tr>
    <tr>
      <td>Q</td>
      <td>R</td>
      <td>S</td>
      <td>T</td>
    </tr>
    <tr>
      <td>U</td>
      <td>V</td>
      <td>W</td>
      <td>X</td>
    </tr>
    <tr>
      <td>Y</td>
      <td>Z</td>
      <td colspan="2">&larr;</td>
    </tr>
  </table>
</div>

app/views/home/_list.html.erb
<section class="card" id="list">
  <header>
    <!--<div  class="button" id="rebuildDb">重建</div>-->
    <div style="width:70px;"></div>
    <h2>八焦</h2>
    <div class="button" id="about"><p>关于</p>
    </div>
  </header>
  <article>
    <div id="staffListWrapper">
      <ul id="staffList">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
    <%= render 'letter_ime' %>
  </article>
</section>

app/views/home/_progress.html.erb
<div class="popMask" style="display:none">
  <div id="progressPop" class="pop">
    <header>写入数据中...</header>
    <div id="progressBar">
      <div id="progressText"></div>
      <div id="progressPercent"></div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div id="wrapper">
  <%= render 'list' %>
</div>
<%= render 'progress' %>
<%= render 'about' %>
<div style="display:none">
  <%= render 'detail' %>
</div>
<%= javascript_include_tag "sea" %>
<%= javascript_include_tag "zepto/zepto", "zepto/event", "zepto/touch", "zepto/ajax", "iscroll" %>
<script>
seajs.use("home/show");
</script>
<script>
var nowVersion = <%=Version.last.time.to_i %>;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>八焦</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0;">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <link rel="apple-touch-icon" sizes="77x77" href="/images/logo.png" />
  <link rel="apple-touch-startup-image" href="/images/startup.png">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <%= stylesheet_link_tag "app.css" %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/user_photos/index.html.erb
<h1>Listing user photos</h1>
<table>
  <tr>
    <th>workno</th>
    <th>photo</th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.workno %></td>
    <td><img src="<%= user_photo_path(photo) %>" /></td>
  </tr>
<% end %>
</table>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>Cnname</th>
    <th>Workno</th>
    <th>Email</th>
    <th>duty</th>
    <th>py</th>
    <th>dept</th>
    <th>quit</th>
    <th>re_cr</th>
    <th>cre</th>
    <th>upd</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.cnname %></td>
    <td><%= user.workno %></td>
    <td><%= user.email %></td>
    <td><%= user.duty %></td>
    <td><%= user.py %></td>
    <td><%= user.dept %></td>
    <td><%= user.quit %></td>
    <td><%= user.re_created_at %></td>
    <td><%= user.created_at %></td>
    <td><%= user.updated_at %></td>
    <td><%= link_to 'Show', user %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cnname:</b>
  <%= @user.cnname %>
</p>

<p>
  <b>Workno:</b>
  <%= @user.workno %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Back', users_path %>